name: Organize Files

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure directory structure
        run: |
          mkdir -p core web/templates web/static/css web/static/js config test_files

      - name: Move files into correct locations
        run: |
          # Core detection logic
          mv -f __init__.py core/ || true
          mv -f secret_detector.py core/ || true
          mv -f file_watcher.py core/ || true
          mv -f logger.py core/ || true

          # Web interface
          mv -f app.py web/ || true
          mv -f index.html web/templates/ || true
          mv -f style.css web/static/css/ || true
          mv -f app.js web/static/js/ || true

          # Config
          mv -f install.sh requirements.txt setup.py config/ || true

          # Tests
          mv -f sample_secrets.py test_files/ || true

          # CLI entry point
          mv -f main.py ./ || true

          # Docs
          if [ -f todo.md ] && [ ! -f README.md ]; then
            mv todo.md README.md
          fi

          # Remove leftover nesting
          rm -rf leakmon || true

      - name: Show git status
        run: |
          git status
          echo "Changes are ready. Push manually or create a PR."
