name: Reorganize Files

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  organize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Move leakmon contents up
        run: |
          # Make sure target dirs exist
          mkdir -p core web config test_files

          # Move everything out of leakmon/
          if [ -d leakmon/core ]; then mv -f leakmon/core ./core/; fi
          if [ -d leakmon/web ]; then mv -f leakmon/web ./web/; fi
          if [ -f leakmon/main.py ]; then mv -f leakmon/main.py ./; fi
          if [ -f leakmon/__init__.py ]; then rm -f leakmon/__init__.py; fi

          # Remove empty leakmon folder
          rm -rf leakmon

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Flatten structure: move leakmon/ contents to repo root" || echo "No changes"
          git push
