name: Organize Files

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  organize:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow commits & pushes
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create directories
        run: |
          mkdir -p core web/templates web/static/css web/static/js config test_files

      - name: Move files into structure
        run: |
          # Python core logic
          mv -f __init__.py core/ || true
          mv -f secret_detector.py core/ || true
          mv -f file_watcher.py core/ || true
          mv -f logger.py core/ || true

          # Web interface
          mv -f app.py web/ || true
          mv -f index.html web/templates/ || true
          mv -f style.css web/static/css/ || true
          mv -f app.js web/static/js/ || true

          # Config & test files
          mv -f sample_secrets.py test_files/ || true
          mv -f requirements.txt setup.py install.sh config/ || true

          # CLI entry point
          mv -f main.py ./ || true

          # If todo.md exists, rename to README.md (if README.md missing)
          if [ -f todo.md ] && [ ! -f README.md ]; then
            mv todo.md README.md
          fi

          # Cleanup any leftover "leakmon" folder
          rm -rf leakmon || true

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-organize repo structure at root" || echo "No changes"
          git push
